/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pdfreader.viewer;

import com.pdfreader.dic.DicVO;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.util.HashSet;
import java.util.Scanner;
import javax.swing.SwingUtilities;

/**
 *
 * @author Trung Pham
 */
public class PDFDicDialog extends javax.swing.JDialog implements IDicDialogSubject {

    /**
     * Creates new form PDFDicDialog
     */
    public static final String ADD_TO_WORD_LIST = "Add to word list";
    public static final String REMOVE_FROM_WORD_LIST = "Remove from word list";
    private DicVO word;
    private HashSet<IDicDialogListener> listeners = new HashSet();

    public PDFDicDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        init();
    }

    private void init() {
        dicPane.setContentType("text/html");
        addWindowFocusListener(new WindowFocusListener() {
            @Override
            public void windowGainedFocus(WindowEvent e) {
            }

            @Override
            public void windowLostFocus(WindowEvent e) {
                setVisible(false);
            }
        });
    }

    public void setAddButtonTitle(String title) {
        addButton.setText(title);
    }

    public String getWord() {
        if (word == null) {
            return null;
        }
        return word.getWord();
    }

    public void setContent(DicVO content) {
        word = content;
        StringBuilder builder = new StringBuilder();
        Scanner scanner = new Scanner(content.getContent());
        wordLabel.setText(content.getWord());
        while (scanner.hasNextLine()) {
            String line = scanner.nextLine();
            builder.append(line).append("<br>");

        }
        dicPane.setText(builder.toString());
        dicPane.validate();
        dicPane.repaint();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                scrollPane.getVerticalScrollBar().setValue(scrollPane.getVerticalScrollBar().getMinimum());
                scrollPane.getHorizontalScrollBar().setValue(scrollPane.getHorizontalScrollBar().getMinimum());
            }
        });

    }

    public void clear() {
        dicPane.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        dicPane = new javax.swing.JTextPane();
        wordLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dicPane.setBackground(new java.awt.Color(204, 204, 255));
        scrollPane.setViewportView(dicPane);

        wordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wordLabel.setText("jLabel1");

        addButton.setText("Add to word list");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton))
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton))
                .addGap(2, 2, 2)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        notifyAddButtonListener();
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PDFDicDialog dialog = new PDFDicDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextPane dicPane;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel wordLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(IDicDialogListener lis) {
        listeners.add(lis);
    }

    @Override
    public void removeListener(IDicDialogListener lis) {
        listeners.remove(lis);
    }

    @Override
    public void notifyAddButtonListener() {
        for (IDicDialogListener lis : listeners) {
            lis.addButtonClick();
        }
    }
}
