/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pdfreader.viewer.workspace;

import com.pdfreader.util.ColorIcon;
import com.pdfreader.util.HTMLHelper;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;

/**
 *
 * @author Trung Pham
 */
public class ColorSectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form ColorSection
     */
    HashSet<ColorSelectionListener> listeners = new HashSet();
    JPopupMenu parent;

    public ColorSectionPanel(JPopupMenu parent) {
        this.parent = parent;
        initComponents();
        init();
    }

    private void init() {
        colorPanel.setLayout(new BorderLayout(0, 0));
        textRadioButton.setSelected(true);
        JPanel buttonPanel = new JPanel(new GridBagLayout());
        buttonPanel.setBackground(Color.WHITE);       
        
        GridBagConstraints c = new GridBagConstraints();
        
        
        int x = 0;
        int y = 0;
        
        JButton[] buttons = new JButton[HTMLHelper.HTMLColor.values().length];
        int index = 0;
        for (final HTMLHelper.HTMLColor color : HTMLHelper.HTMLColor.values()) {
            buttons[index] = new JButton();
            ColorIcon icon = new ColorIcon(30, 30, new Color(color.getNumber()));
            buttons[index].setIcon(icon);           
            buttons[index].setMargin(new Insets(0, 0, 0, 0));
            buttons[index].setContentAreaFilled(false);
            buttons[index].addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    notifyListeners(textRadioButton.isSelected(), color);
                    parent.setVisible(false);
                }
            });

            c.fill = GridBagConstraints.HORIZONTAL;
            c.gridx = x++;
            c.gridy = y;
            if( x == 3){
                x = 0;                
                y++;               
            }
            buttonPanel.add(buttons[index], c);
            index++;
        }
        colorPanel.add(buttonPanel , BorderLayout.CENTER);
    }

    public void addListener(ColorSelectionListener lis) {
        listeners.add(lis);
    }

    public void notifyListeners(boolean text, HTMLHelper.HTMLColor color) {
        for (ColorSelectionListener lis : listeners) {
            lis.colorSelection(text, color);
        }
    }

   
    public static interface ColorSelectionListener {

        public void colorSelection(boolean text, HTMLHelper.HTMLColor color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textRadioButton = new javax.swing.JRadioButton();
        highlightRadioButton = new javax.swing.JRadioButton();
        colorPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        textRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(textRadioButton);
        textRadioButton.setText("Text");
        textRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        highlightRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(highlightRadioButton);
        highlightRadioButton.setText("Hightlight");
        highlightRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highlightRadioButtonActionPerformed(evt);
            }
        });

        colorPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(textRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(highlightRadioButton))
            .addComponent(colorPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRadioButton)
                    .addComponent(highlightRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void highlightRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highlightRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highlightRadioButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JRadioButton highlightRadioButton;
    private javax.swing.JRadioButton textRadioButton;
    // End of variables declaration//GEN-END:variables
}
