/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pdfreader.viewer.workspace;

/**
 *
 * @author Trung Pham
 */
public class PDFMapPanel extends javax.swing.JPanel {

    /**
     * Creates new form PDFMapPanel
     */
    public PDFMapPanel() {
        initComponents();
    }

    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pDFSummaryPanel1 = new com.pdfreader.viewer.workspace.PDFSummaryPanel();
        pDFSummaryPanel2 = new com.pdfreader.viewer.workspace.PDFSummaryPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        storePanel = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(350);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setTopComponent(pDFSummaryPanel1);
        jSplitPane1.setTopComponent(pDFSummaryPanel2);
        jSplitPane1.setRightComponent(jScrollBar1);

        javax.swing.GroupLayout storePanelLayout = new javax.swing.GroupLayout(storePanel);
        storePanel.setLayout(storePanelLayout);
        storePanelLayout.setHorizontalGroup(
            storePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        storePanelLayout.setVerticalGroup(
            storePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jSplitPane1.setBottomComponent(storePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSplitPane jSplitPane1;
    private com.pdfreader.viewer.workspace.PDFSummaryPanel pDFSummaryPanel1;
    private com.pdfreader.viewer.workspace.PDFSummaryPanel pDFSummaryPanel2;
    private javax.swing.JPanel storePanel;
    // End of variables declaration//GEN-END:variables
}
