/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pdfreader.viewer.wordlist;

import java.util.HashSet;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Trung Pham
 */
public class WordListPanel extends javax.swing.JPanel implements IWordListPanelSubject {

    private HashSet<IWordListPanelListener> listeners = new HashSet();
    private DefaultListModel<String> model;

    public WordListPanel() {
        initComponents();
    }

    public void populateListContent(List<String> content) {
        model = new DefaultListModel();
        for (String word : content) {
            model.addElement(word);
        }
        wordList.setModel(model);
        wordList.revalidate();
    }

    public void addWord(String word) {
        model.addElement(word);
        wordList.setModel(model);
        wordList.revalidate();
    }

    public void removeWord(String word) {
        model.removeElement(word);
        wordList.setModel(model);
        wordList.revalidate();
    }

    public String getSelectedWord() {
        if (wordList.getSelectedValue() == null) {
            return null;
        }
        return wordList.getSelectedValue().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        wordList = new javax.swing.JList();

        wordList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        wordList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(wordList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wordListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordListMouseClicked
        notifyListener();
    }//GEN-LAST:event_wordListMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList wordList;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addListener(IWordListPanelListener lis) {
        listeners.add(lis);
    }

    @Override
    public void removeListener(IWordListPanelListener lis) {
        listeners.remove(lis);
    }

    @Override
    public void notifyListener() {
        for (IWordListPanelListener list : listeners) {
            list.mouseClick();
        }
    }
}
